---
- id: yactionlint
  name: Lint GitHub Actions workflow files
  description: Runs yactionlint to lint GitHub Actions workflow files
  language: golang
  types: ["yaml"]
  files: ^\.github/workflows/
  entry: yactionlint
  minimum_pre_commit_version: 3.0.0
- id: yactionlint-system
  name: Lint GitHub Actions workflow files
  description: Runs system-installed yactionlint to lint GitHub Actions workflow files
  language: system
  types: ["yaml"]
  files: ^\.github/workflows/
  entry: yactionlint
