name: Generate
on:
  push:
    paths:
      - 'scripts/generate-popular-actions/main.go'
      - 'scripts/generate-webhook-events/main.go'
    branches:
      - main
    tags-ignore:
      - '*'
  schedule:
    # Every Saturday 10:21 in JST
    - cron: '21 1 * * 6'
  workflow_dispatch:

jobs:
  go-generate:
    if: ${{ github.repository == 'mkusaka/actionlint' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          check-latest: true
      - name: Check new release on GitHub
        run: go run ./scripts/generate-popular-actions -d
      - run: go generate
      - run: |
          if git diff-files --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            git diff
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        id: diff
      - name: Commit generated files
        if: ${{ steps.diff.outputs.changed == 'true' }}
        run: |
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          git add all_webhooks.go availability.go popular_actions.go
          git commit -m 'update generated files by go generate on CI'
          git push
