name: Release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: gem install ronn
      - run: ronn --roff ./man/yactionlint.1.ronn
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          check-latest: true
      - name: Get version
        run: echo VERSION="${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"
      - uses: goreleaser/goreleaser-action@v7
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/attest-build-provenance@v4
        with:
          subject-checksums: ${{ format('./dist/yactionlint_{0}_checksums.txt', env.VERSION) }}
      - name: Post-release download check
        run: bash ./scripts/download-yactionlint.bash "$VERSION"
